image:
  file: .gitpod.Dockerfile

tasks:
  - before: molecule create # executed on every start and is expected to terminate

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
