---
- name: Converge
  hosts: all
  tasks:
    - name: "Include lorenzobettini.oh_my_zsh"
      ansible.builtin.include_role:
        name: "lorenzobettini.oh_my_zsh"
      vars:
        with_starship: false
        copy_dot_files: false
