---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-archlinux:latest}
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
verifier:
  name: ansible
