---
# tasks file for oh_my_zsh
- name: Install Git
  become: yes
  ansible.builtin.package:
    state: present
    name: git

- name: Install ZSH
  become: yes
  ansible.builtin.package:
    name: zsh
    state: present

- name: Install Powerline fonts
  become: yes
  ansible.builtin.package:
    state: present
    name: powerline-fonts

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Change user shell to zsh 
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh