---
# tasks file for oh_my_zsh
- name: Install Git
  become: true
  ansible.builtin.package:
    state: present
    name: git

- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Override powerline fonts package name for Debian.
  ansible.builtin.set_fact:
    powerlinefonts: fonts-powerline
  when: ansible_os_family == 'Debian'

- name: Override fd-find package name for Archlinux.
  ansible.builtin.set_fact:
    fdfind: fd
  when: ansible_os_family == 'Archlinux'

- name: Install Powerline fonts
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ powerlinefonts }}"

- name: Install fd-find
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ fdfind }}"

# required by the OMZ plugin zsh-interactive-cd
- name: Install fzf (command-line fuzzy finder)
  become: true
  ansible.builtin.package:
    state: present
    name: fzf

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Tasks for starship
  ansible.builtin.include_tasks: starship.yml
  when: with_starship

- name: Tasks for p10k
  ansible.builtin.include_tasks: p10k.yml
  when: not with_starship
