---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE_DISTRO:-archlinux:latest}
    image: ${MOLECULE_DISTRO:-archlinux:latest}
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
