---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-fedora:36}
    pre_build_image: true
provisioner:
  name: ansible
  env:
    DISTRO: ${MOLECULE_DISTRO}
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
