---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Environment MOLECULE_DISTRO
      ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'MOLECULE_DISTRO') }}'"

    - name: Environment DISTRO
      ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'DISTRO') }}'"

    - name: Install python
      ansible.builtin.raw: pacman -Sy --noconfirm --needed python sudo
