---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python in Arch
      ansible.builtin.raw: pacman -Sy --noconfirm --needed python sudo
      when: "'arch' is in lookup('ansible.builtin.env', 'MOLECULE_DISTRO')"
