---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python in Ubuntu
      ansible.builtin.raw: apt update && apt install -y --no-install-recommends python3 sudo
      changed_when: false