---
name: Molecule CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        playbookdistro:
          - fedora:36
          - archlinux:latest
          - ubuntu:jammy

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Cache pip installed packages
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/Python/*/x64/lib/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ matrix.playbookdistro }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-

      - name: Install test dependencies.
        run: pip install -r pip/requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.playbookdistro }}